import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Preline_Navbar from "./preline/Preline_Navbar";
import PrelineScript from "./preline/PrelineScript";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* navbar */}
        <Preline_Navbar />

        {/* body */}
        {children}

        {/* preline script */}
        <PrelineScript />
      </body>
    </html>
  );
}
